// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daxtzlsrbugbjpzxwjtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheHR6bHNyYnVnYmpwend3anRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4NTI4MDAsImV4cCI6MjAyNjQyODgwMH0.ZxVDB7TYVXm6sK2vK4ENVfwTdWZYaXe4LxDQGHc0EYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);